version: '3.8'

services:
  se-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: nyouko/space-engineer:latest
    container_name: se-ds-docker
    restart: unless-stopped

    volumes:
      # Montages persistants : NE PAS modifier les chemins de droite
      - /space-engineers/plugins:/mnt/plugins
      - /space-engineers/instances:/mnt/instances
      - /space-engineers/SpaceEngineersDedicated:/mnt/SpaceEngineersDedicated
      - /space-engineers/steamcmd:/home/authaurizeduser/.steam

    ports:
      # Ports en mode host pour compatibilité réseau
      - target: 27016
        published: 27016
        protocol: udp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 8766
        published: 8766
        protocol: udp
        mode: host

    environment:
      WINEDEBUG: "-all"
      INSTANCE_NAME: "SE"
      WORLD_NAME: "World"
      WORLD_TEMPLATE: "Home System"
      OFFLINE: "false"
      CREATIVE: "false"
      CROSSPLATFORM: "true"
      EXPERIMENTALMODE: "true"
      INGAMESCRIPT: "true"
      PAUSEGAMEWHENEMPTY: "true"
      NBR_PLAYER: "8"
      PUBLIC_IP: "127.0.0.1"

    labels:
      com.nyouko.space-engineers.maintainer: "Nyouko"
      com.nyouko.space-engineers.description: "Space Engineers Dedicated Server via Wine in Docker"
