version: "3.8"

services:
  spaceengineers:
    build: .
    container_name: spaceengineers
    restart: unless-stopped

    # Ports requis pour Space Engineers
    ports:
      - "27016:27016/udp"   # Game port
      - "27015:27015/udp"   # Steam query port (optionnel)
      - "8080:8080/tcp"     # API port

    volumes:
      - ./data/instance:/home/spaceuser/.wine/drive_c/spaceengineers
      - ./data/config:/home/spaceuser/.config/spaceengineers
      - ./logs:/home/spaceuser/logs

    environment:
      - WINEPREFIX=/home/spaceuser/.wine
      - DISPLAY=:0
      - TZ=Europe/Paris  # Adapte à ton fuseau horaire

    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5

    security_opt:
      - no-new-privileges:true

    cap_drop:
      - ALL

    read_only: true

    tmpfs:
      - /tmp
      - /home/spaceuser/.wine/drive_c/users/spaceuser/Temp

