#!/bin/bash

# VARIABLES
if [ -z "$INSTANCE_NAME" ]; then
  INSTANCE_NAME="autogenerated"
fi
if [ -z "$WORLD_NAME" ]; then
  WORLD_NAME="World"
fi
if [ -z "$WORLD_TEMPLATE" ]; then
  WORLD_TEMPLATE="Home System"
fi
if [ "$OFFLINE" = "true" ]; then
  OFFLINE="OFFLINE"
else
  OFFLINE="PUBLIC"
fi
if [ "$CREATIVE" = "true" ]; then
  CREATIVE="Creative"
else
  CREATIVE="Survival"
fi
if [ ! "$CROSSPLATFORM" = "true" ]; then
  CROSSPLATFORM="false"
fi
if [ ! "$EXPERIMENTALMODE" = "true" ]; then
  EXPERIMENTALMODE="false"
fi
if [ ! "$INGAMESCRIPT" = "true" ]; then
  INGAMESCRIPT="false"
fi
if [ ! "$PAUSEGAMEWHENEMPTY" = "true" ]; then
  PAUSEGAMEWHENEMPTY="false"
fi
if ! [[ "$NBR_PLAYER" =~ ^[0-9]+$ ]]; then
  NBR_PLAYER=6
fi
GAME_DIR="/mnt/SpaceEngineersDedicated"
INSTANCE_DIR="/mnt/instances/${INSTANCE_NAME}"
PLUGIN_DIR="/mnt/plugins"
WORLD_PATH="${INSTANCE_DIR}/Saves/${WORLD_NAME}/Sandbox_config.sbc"
CONFIG_PATH="${INSTANCE_DIR}/SpaceEngineers-Dedicated.cfg"
LAUNCHER="${GAME_DIR}/DedicatedServer64/SpaceEngineersDedicated.exe"
SAVE_PATH="${INSTANCE_DIR}/Saves/${WORLD_NAME}"
SAVE_PATH_CONVERT="Z:$(echo "$SAVE_PATH" | sed 's/\//\\\//g')"

echo "-------------------------------INSTALL & UPDATE------------------------------"
echo "-------------------------------Installation of the game"
/opt/steamcmd/steamcmd.sh +force_install_dir ${GAME_DIR} +login anonymous +@sSteamCmdForcePlatformType windows +app_update 298740 +quit
mkdir -p "${INSTANCE_DIR}/Old-Logs" "${INSTANCE_DIR}/Saves/${WORLD_NAME}"

if [ -d "${INSTANCE_DIR}/Saves/${WORLD_NAME}" ] && [ -z "$(ls -A "${INSTANCE_DIR}/Saves/${WORLD_NAME}")" ]; then
  echo "-------------------------------Chargement du template de la map"
  cp -r "${GAME_DIR}/Content/CustomWorlds/${WORLD_TEMPLATE}/." "${INSTANCE_DIR}/Saves/${WORLD_NAME}/"
fi

if ! test -e "${CONFIG_PATH}"; then
  echo "-------------------------------Pré-lancement du serveur"
  wine "${LAUNCHER}" -noconsole -ignorelastsession -path "${INSTANCE_DIR}" &> /dev/null
fi
echo "---------------------------------UPDATE CONFIG-------------------------------"
sed -i "s=<IP>.*</IP>=<IP>0.0.0.0</IP>=g" "${CONFIG_PATH}"

echo "GameMode: ${CREATIVE}"
sed -i "s=<GameMode>.*</GameMode>=<GameMode>${CREATIVE}</GameMode>=g" "${CONFIG_PATH}" "${WORLD_PATH}"

echo "OnlineMode: ${OFFLINE}"
sed -i "s=<OnlineMode>.*</OnlineMode>=<OnlineMode>${OFFLINE}</OnlineMode>=g" "${CONFIG_PATH}" "${WORLD_PATH}"

echo "MaxPlayers: ${NBR_PLAYER}"
sed -i "s=<MaxPlayers>.*</MaxPlayers>=<MaxPlayers>${NBR_PLAYER}</MaxPlayers>=g" "${CONFIG_PATH}" "${WORLD_PATH}"

echo "ServerName: ${INSTANCE_NAME}"
sed -i "s|<ServerName\s*/>|<ServerName>${INSTANCE_NAME}</ServerName>|g" "${CONFIG_PATH}"
sed -i "s|<ServerName>.*</ServerName>|<ServerName>${INSTANCE_NAME}</ServerName>|g" "${CONFIG_PATH}"

echo "WorldName: ${WORLD_NAME}"
sed -i "s|<WorldName\s*/>|<WorldName>${WORLD_NAME}</WorldName>|g" "${CONFIG_PATH}"
sed -i "s|<WorldName>.*</WorldName>|<WorldName>${WORLD_NAME}</WorldName>|g" "${CONFIG_PATH}"

echo "CrossPlatform: ${CROSSPLATFORM}"
sed -i "s=<CrossPlatform>.*</CrossPlatform>=<CrossPlatform>${CROSSPLATFORM}</CrossPlatform>=g" "${CONFIG_PATH}"

echo "ExperimentalMode: ${EXPERIMENTALMODE}"
sed -i "s=<ExperimentalMode>.*</ExperimentalMode>=<ExperimentalMode>${EXPERIMENTALMODE}</ExperimentalMode>=g" "${CONFIG_PATH}" "${WORLD_PATH}"

echo "EnableIngameScripts: ${INGAMESCRIPT}"
sed -i "s=<EnableIngameScripts>.*</EnableIngameScripts>=<EnableIngameScripts>${INGAMESCRIPT}</EnableIngameScripts>=g" "${CONFIG_PATH}" "${WORLD_PATH}"

echo "PauseGameWhenEmpty: ${PAUSEGAMEWHENEMPTY}"
sed -i "s=<PauseGameWhenEmpty>.*</PauseGameWhenEmpty>=<PauseGameWhenEmpty>${PAUSEGAMEWHENEMPTY}</PauseGameWhenEmpty>=g" "${CONFIG_PATH}"

echo "Clear BlockTypeLimits dictionary"
sed -i '/<dictionary>/,/<\/dictionary>/c\<dictionary />' "${CONFIG_PATH}"


# update world save path
sed -E -i "s|<LoadWorld>.*</LoadWorld>|<LoadWorld>${SAVE_PATH_CONVERT}</LoadWorld>|g" "${CONFIG_PATH}"

# Si la balise n'existait pas, l'insérer après </SessionSettings>
if ! grep -q "<LoadWorld>" "${CONFIG_PATH}"; then
  sed -i "/<\/SessionSettings>/a <LoadWorld>${SAVE_PATH_CONVERT}</LoadWorld>" "${CONFIG_PATH}"
fi


echo "---------------------------------UPDATE PLUGINS------------------------------"
PLUGIN_COUNT=$(ls -1 ${PLUGIN_DIR}/*.dll 2> /dev/null | wc -l)
echo "Found ${PLUGIN_COUNT} plugin(s) in ${PLUGIN_DIR}"

if [ "${PLUGIN_COUNT}" -gt "0" ]; then
  PLUGINS_STRING="<Plugins>$(ls -1 ${PLUGIN_DIR}/*.dll |\
  sed -E "s=(.+\.dll)=<string>\1</string>=g" |\
  tr -d "\n" )</Plugins>"
else
  PLUGINS_STRING="<Plugins />"
fi

sed -E -i "s=<Plugins />|<Plugins.*Plugins>=${PLUGINS_STRING}=g" "${CONFIG_PATH}"

echo "-----------------------------CURRENT CONFIGURATION---------------------------"
echo "GAME_DIR=$GAME_DIR"
echo "CONFIG_PATH=$CONFIG_PATH"
echo "SAVE_PATH=$SAVE_PATH"
echo "INSTANCE_DIR=$INSTANCE_DIR"
## END UPDATES ##
wine --version
echo "----------------------------------START GAME---------------------------------"
mv ${INSTANCE_DIR}/*.log ${INSTANCE_DIR}/Old-Logs/ 2> /dev/null
chmod -R 777 "${INSTANCE_DIR}"
wine "${LAUNCHER}" -noconsole -ignorelastsession -path "${INSTANCE_DIR}"
chmod -R 777 "${INSTANCE_DIR}"
echo "-----------------------------------END GAME----------------------------------"